name: Build & Test

on:
  push:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
  pull_request:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['Windows-latest', 'ubuntu-latest', 'macOS-latest']
        
    defaults:
      run:
        shell: pwsh
    
    runs-on: ${{ matrix.os }}
    
    name: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

      # https://github.com/actions/setup-dotnet/issues/155
    - name: Resetting nuget
      run: |
        dotnet clean -c Release && dotnet nuget locals all --clear
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build -c Release --no-restore

    - name: Test 
      run: dotnet test -c Release --no-restore --verbosity normal
      
